project: dot
providers:
  google_secretmanager:
    env:
      REGISTRY_SERVER:
        path: projects/vfarcic/secrets/github-registry/versions/1
      REGISTRY_USER:
        path: projects/vfarcic/secrets/github-user/versions/1
      REGISTRY_PASSWORD:
        path: projects/vfarcic/secrets/github-token/versions/2
      AZURE_TENANT_ID:
        path: projects/vfarcic/secrets/azure-tenant/versions/1
      AWS_ACCESS_KEY_ID:
        path: projects/vfarcic/secrets/aws-access-key-id/versions/4
      AWS_SECRET_ACCESS_KEY:
        path: projects/vfarcic/secrets/aws-secret-access-key/versions/4
      AWS_ACCOUNT_ID:
        path: projects/vfarcic/secrets/aws-account-id/versions/1
