apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: silly-demo
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: my-db
        key: conn-my-db
