apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-1
managedNodeGroups:
- name: primary
  instanceType: t2.medium
  minSize: 3
  maxSize: 6
  spot: true
