---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: openfunction-demo
spec:
  version: "v2.0.0"
  image: "ghcr.io/vfarcic/crossplane-openfunction-dapr-demo:v0.0.1"
  imageCredentials:
    name: push-secret
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
      openfunction.io/dapr-service-mode: "standalone"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: my-db
                  key: endpoint
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: my-db
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-db
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-db
                  key: password
            - name: DB_NAME
              value: my-db
    triggers:
      http:
        port: 8080
  build:
    builder: openfunction/builder-go:v2.4.0-1.17
    env:
      FUNC_NAME: SillyDemo
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: https://github.com/vfarcic/crossplane-openfunction-dapr-demo
      revision: main
