---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: openfunction-demo
spec:
  version: "v2.0.0"
  image: "ghcr.io/vfarcic/crossplane-openfunction-dapr-demo:v0.0.1"
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v2.4.0-1.17
    env:
      FUNC_NAME: SillyDemo
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: https://github.com/vfarcic/crossplane-openfunction-dapr-demo
      revision: main
  serving:
    annotations:
      openfunction.io/enable-dapr: "true"
      openfunction.io/dapr-service-mode: "sidecar"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
          env:
            - name: STATESTORE_NAME
              value: my-db-my-db
    triggers:
      http:
        port: 8080
