apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: accessKeyID
            namespace: crossplane-system
          secretAccessKeySecretRef:
            name: aws-creds
            key: secretAccessKey
            namespace: crossplane-system
