apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: cluster
spec:
  id: a-team-cluster
  compositionSelector:
    matchLabels:
      provider: google
      cluster: gke
  parameters:
    nodeSize: medium
    minNodeCount: 1
    namespaces:
      - dev
      - production
      - crossplane-system
    apps:
      openfunction:
        enabled: true
      externalSecrets:
        enabled: true
        store: true
    creds:
      name: gcp-creds
      namespace: crossplane-system
      key: creds
